### ISSUE TITLE
The use of `gpg --show-keys` is causing errors in Bionic builds

### ISSUE THREAD

**Issue by azeey** [gazebo-tooling/gzdev#76]
https://github.com/gazebo-tooling/gzdev/blob/54525bca22f4253f0ffd37be12bc07dc24250f11/plugins/repository.py#L121

Example build: https://build.osrfoundation.org/job/sdformat9-debbuilder/205/console
```
#18 [14/45] RUN /home/jenkins/workspace/sdformat9-debbuilder/gzdev/gzdev.py repository enable osrf stable --force-linux-distro=bionic --keyserver hkps://pgp.surf.nl || ( git -C /home/jenkins/workspace/sdformat9-debbuilder/gzdev pull origin master &&     if [ -n  ]; then git -C /home/jenkins/workspace/sdformat9-debbuilder/gzdev checkout ; fi || true &&     /home/jenkins/workspace/sdformat9-debbuilder/gzdev/gzdev.py repository enable osrf stable --force-linux-distro=bionic --keyserver hkps://pgp.surf.nl)
#18 0.667 gpg: invalid option "--show-keys"
#18 0.667 
#18 0.667  [warn] --keyserver option is deprecated. It is safe to remove it
#18 0.667 
#18 0.668 Traceback (most recent call last):
#18 0.668   File "/home/jenkins/workspace/sdformat9-debbuilder/gzdev/gzdev.py", line 36, in <module>
#18 0.668     plugin.main()
#18 0.668   File "/home/jenkins/workspace/sdformat9-debbuilder/gzdev/plugins/repository.py", line 234, in main
#18 0.668     process_input(args, config)
#18 0.668   File "/home/jenkins/workspace/sdformat9-debbuilder/gzdev/plugins/repository.py", line 223, in process_input
#18 0.668     install_repo(repo_name, repo_type, config, linux_distro)
#18 0.668   File "/home/jenkins/workspace/sdformat9-debbuilder/gzdev/plugins/repository.py", line 168, in install_repo
#18 0.668     assert_key_in_file(key, key_path)
#18 0.668   File "/home/jenkins/workspace/sdformat9-debbuilder/gzdev/plugins/repository.py", line 121, in assert_key_in_file
#18 0.668     ['gpg', '--show-keys', key_path])
#18 0.668   File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
#18 0.668     **kwargs).stdout
#18 0.668   File "/usr/lib/python3.6/subprocess.py", line 438, in run
#18 0.668     output=stdout, stderr=stderr)
#18 0.668 subprocess.CalledProcessError: Command '['gpg', '--show-keys', '/usr/share/keyrings/_gzdev_osrf_stable.gpg']' returned non-zero exit status 2.
```

**Comment by azeey** [comment]
I realized after opening this issue that we've been removing Bionic builds (see https://github.com/gazebo-release/gz-transport11-release/pull/15), so maybe that's the solution. Feel free to close.
